language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - nightly
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

matrix:
  fast_finish: true

install:
  - composer require cundd/test-flight phpmd/phpmd

script:
  - vendor/bin/phpunit
  - vendor/bin/test-flight README.md
  - vendor/bin/test-flight classes/
  - vendor/bin/phpcs
  - vendor/bin/phpmd classes/ text cleancode,codesize,controversial,design,naming,unusedcode
